#!/usr/bin/env python3
"""Make the feature dictionary analysis-ready without touching raw input."""
from pathlib import Path
import pandas as pd

R=Path(__file__).resolve().parents[1]; C=R/'catalog'; P=R/'processed'
# Never infer raw-indicator meanings from their codes.  The preserved official
# e-Stat metadata label is the display authority; label_en intentionally only
# identifies provenance rather than making an unverified translation.
DERIVED={'commuters':('commuting/schooling population denominator','Census/SSDS transport total; denominator differs by documented census table/year','raw outcome component'),'rail_users':('rail/electric-train users','Census/SSDS transport category sum; category codes recorded in methodology','raw outcome component'),'car_users':('private-car users','SSDS H730105','contextual transport outcome component'),'bike_users':('bicycle users','SSDS H730111','contextual transport outcome component'),'rail_any_share':('rail/electric-train use share','rail_users / commuters; non-exclusive mode numerator','primary outcome'),'car_any_share':('private-car use share','car_users / commuters; non-exclusive mode numerator','contextual outcome'),'bike_share':('bicycle use share','bike_users / commuters; non-exclusive mode numerator','contextual outcome'),'population_density':('population density','A1101 / B1101; denominator > 0','derived predictor'),'aging_share_65plus':('age 65+ share','A1303 / A1101; denominator > 0','derived predictor'),'share_75plus':('age 75+ share','A1419 / A1101; denominator > 0','derived predictor'),'working_age_share_15_64':('working-age share','A1302 / A1101; denominator > 0','derived predictor'),'youth_share_0_14':('youth share','A1301 / A1101; denominator > 0','derived predictor'),'log_population':('log population','log1p(A1101)','derived predictor'),'foreign_population_share':('foreign population share','A1700 / A1101; denominator > 0','derived predictor'),'single_household_share':('single-person household share','A810105 / A710101; denominator > 0','derived predictor'),'elderly_single_household_share':('elderly single-person household share','A8301 / A710101; denominator > 0','derived predictor'),'unemployment_rate':('unemployment rate','F1107 / (F1102 + F1107); denominator > 0','derived predictor'),'non_labor_force_share':('non-labor-force share','F1108 / (F1102 + F1107 + F1108); denominator > 0','derived predictor'),'primary_industry_share':('primary industry employment share','F2201 / (F2201 + F2211 + F2221); denominator > 0','derived predictor'),'secondary_industry_share':('secondary industry employment share','F2211 / (F2201 + F2211 + F2221); denominator > 0','derived predictor'),'tertiary_industry_share':('tertiary industry employment share','F2221 / (F2201 + F2211 + F2221); denominator > 0','derived predictor'),'log_commuters':('log commuting/schooling population','log1p(commuters)','derived, descriptive only'),'rail_pp':('rail use share, percentage points','100 * rail_any_share','derived, descriptive only')}
def main():
 raw=pd.read_parquet(C/'data_dictionary.parquet').drop_duplicates('feature'); panel=pd.read_parquet(P/'municipality_panel.parquet'); source=pd.read_parquet(C/'source_registry.parquet')
 retrieved='; '.join(sorted(source.retrieved_at.dropna().astype(str).unique())[:5]); rows=[]
 for feature in panel.columns:
  if feature in {'code','year'}: continue
  x=panel[feature]; years=','.join(map(str,sorted(panel.loc[x.notna(),'year'].unique()))); base=raw[raw.feature==feature]
  if feature in DERIVED:
   label,definition,role=DERIVED[feature]; rows.append({'feature':feature,'label_en':label,'official_item_name_raw':None,'source_stat':'derived from e-Stat inputs','stat_table_id':None,'item_code':None,'unit':'proportion' if 'share' in feature else 'count / transformed count','observation_years':years,'raw_or_derived':'derived','transformation_or_definition':definition,'analysis_role':role,'missing_rate_panel':float(x.isna().mean()),'retrieval_recorded_at':retrieved,'metadata_note':'Formula is defined here; source components are separately listed.'})
  elif not base.empty:
   b=base.iloc[0]; rows.append({'feature':feature,'label_en':'Official e-Stat municipal indicator '+feature,'label_safe':b.item_name,'official_item_name_raw':b.item_name,'source_stat':b.source_stat,'stat_table_id':str(b.stat_table_id),'item_code':feature,'unit':'See preserved e-Stat metadata @unit','observation_years':years,'raw_or_derived':'raw','transformation_or_definition':'No panel transformation; model-time imputation/scaling is fit inside folds.','analysis_role':'candidate socioeconomic predictor','missing_rate_panel':float(x.isna().mean()),'retrieval_recorded_at':retrieved,'metadata_note':'Official metadata retained under data/raw/ssds_metadata and data/raw/ssds_core; no hand-translated raw label is used.'})
  else:
   rows.append({'feature':feature,'label_en':feature,'official_item_name_raw':None,'source_stat':'panel identifier','stat_table_id':None,'item_code':None,'unit':'code/year/name','observation_years':years,'raw_or_derived':'identifier','transformation_or_definition':'municipality code join key or observation time/name field','analysis_role':'identifier','missing_rate_panel':float(x.isna().mean()),'retrieval_recorded_at':None,'metadata_note':''})
 # The compact historical temporal covariates are intentionally separate from
 # the SSDS 2010/2020 panel.  Their code-level source is recorded here too.
 rows += [
  {'feature':'population_total_2000','label_en':'Official e-Stat Census item (2000 temporal input)','label_safe':'cat02=T01, cat01=000, cat03=000','official_item_name_raw':'cat02=T01, cat01=000, cat03=000','source_stat':'e-Stat 2000 Census','stat_table_id':'0000033332','item_code':'cat01=000;cat02=T01;cat03=000','unit':'persons','observation_years':'2000','raw_or_derived':'raw','transformation_or_definition':'Direct Census value; temporal training input only.','analysis_role':'temporal socioeconomic predictor','missing_rate_panel':None,'retrieval_recorded_at':retrieved,'metadata_note':'Raw request manifest under data/raw/census_2000_ses_age.'},
  {'feature':'aging_share_65plus_2000','label_en':'age 65+ share (2000 temporal input)','official_item_name_raw':'cat02=565 / cat02=T01','source_stat':'e-Stat 2000 Census','stat_table_id':'0000033332','item_code':'cat01=000;cat02=565,T01;cat03=000','unit':'proportion','observation_years':'2000','raw_or_derived':'derived','transformation_or_definition':'population age 65+ / total population.','analysis_role':'temporal socioeconomic predictor','missing_rate_panel':None,'retrieval_recorded_at':retrieved,'metadata_note':'Raw request manifest under data/raw/census_2000_ses_age.'},
  {'feature':'working_age_share_15_64_2000','label_en':'age 15-64 share (2000 temporal input)','official_item_name_raw':'(cat02=415 - cat02=565) / cat02=T01','source_stat':'e-Stat 2000 Census','stat_table_id':'0000033332','item_code':'cat01=000;cat02=415,565,T01;cat03=000','unit':'proportion','observation_years':'2000','raw_or_derived':'derived','transformation_or_definition':'(population age 15+ - population age 65+) / total population.','analysis_role':'temporal socioeconomic predictor','missing_rate_panel':None,'retrieval_recorded_at':retrieved,'metadata_note':'Raw request manifest under data/raw/census_2000_ses_age.'}
 ]
 out=pd.DataFrame(rows)
 out['source_dataset']=out.source_stat; out['ssdse_version']=None; out['ssdse_item_code']=None; out['reference_year']=None; out['formula']=out.transformation_or_definition; out['temporal_safe']=None; out['source_url']=None
 sm=C/'ssdse_a_2026_item_metadata.csv'
 if sm.exists():
  m=pd.read_csv(sm).set_index('feature')
  for i,r in out.iterrows():
   if r.feature in m.index:
    q=m.loc[r.feature]; out.loc[i,['source_dataset','ssdse_version','ssdse_item_code','reference_year','temporal_safe','source_url']]=['SSDSE-A-2026','2026',q.ssdse_item_code,q.reference_year,bool(q.temporal_safe),q.source_url]
  for f in ['log_population','aging_share_65plus','share_75plus','youth_share_0_14','working_age_share_15_64','foreign_population_share','single_household_share','elderly_single_household_share','unemployment_rate','non_labor_force_share','primary_industry_share','secondary_industry_share','tertiary_industry_share']:
   out.loc[out.feature.eq(f),'source_dataset']='SSDSE-A-2026 derived'; out.loc[out.feature.eq(f),'ssdse_version']='2026'; out.loc[out.feature.eq(f),'temporal_safe']=True; out.loc[out.feature.eq(f),'source_url']='https://www.nstac.go.jp/files/SSDSE-A-2026.csv'
 out.to_parquet(C/'data_dictionary_enhanced.parquet',index=False); out.to_csv(C/'feature_dictionary.csv',index=False,encoding='utf-8-sig'); out.to_parquet(C/'feature_dictionary.parquet',index=False); print(f'wrote {len(out)} analysis fields; {out.raw_or_derived.value_counts().to_dict()}')
if __name__=='__main__': main()
